package com.vtop.ui.core

import android.annotation.SuppressLint
import android.content.ContentValues
import android.content.Context
import android.provider.CalendarContract
import android.widget.Toast
import androidx.work.Data
import androidx.work.OneTimeWorkRequestBuilder
import androidx.work.WorkManager
import com.vtop.models.ExamScheduleModel
import com.vtop.models.TimetableModel
import com.vtop.ui.screens.main.ProcessedCourse
import com.vtop.ui.screens.main.processAndMergeCourses
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*
import java.util.concurrent.TimeUnit

data class CalendarInfo(val id: Long, val name: String, val accountName: String)

data class BunkCacheData(
    val lastInstructionalDay: String,
    val blockedDates: Map<Calendar, String>,
    val examStartDates: Map<String, Calendar>
)

object CalendarSync {

    private const val VTOP_SYNC_FOOTPRINT = "\n\n[Generated by VTOP app]"

    private fun String?.cleanStr(): String {
        if (this == null || this.isBlank() || this.trim() == "-" || this.trim().equals("TBD", true) || this.trim().equals("N/A", true) || this.trim().equals("null", true)) {
            return " "
        }
        return this.trim()
    }

    @SuppressLint("Range")
    fun getWritableCalendars(context: Context): List<CalendarInfo> {
        val calendars = mutableListOf<CalendarInfo>()
        val projection = arrayOf(
            CalendarContract.Calendars._ID,
            CalendarContract.Calendars.CALENDAR_DISPLAY_NAME,
            CalendarContract.Calendars.ACCOUNT_NAME,
            CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL
        )
        val selection = "${CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL} >= ?"
        val selectionArgs = arrayOf(CalendarContract.Calendars.CAL_ACCESS_CONTRIBUTOR.toString())

        val cursor = context.contentResolver.query(CalendarContract.Calendars.CONTENT_URI, projection, selection, selectionArgs, null)
        cursor?.use {
            while (it.moveToNext()) {
                val id = it.getLong(it.getColumnIndex(CalendarContract.Calendars._ID))
                val name = it.getString(it.getColumnIndex(CalendarContract.Calendars.CALENDAR_DISPLAY_NAME)) ?: "Calendar"
                val account = it.getString(it.getColumnIndex(CalendarContract.Calendars.ACCOUNT_NAME)) ?: ""
                calendars.add(CalendarInfo(id, name, account))
            }
        }
        return calendars
    }

    fun clearSyncedEvents(context: Context, calendarId: Long) {
        try {
            val selection = "(${CalendarContract.Events.CALENDAR_ID} = ?) AND (${CalendarContract.Events.DESCRIPTION} LIKE ?)"
            val selectionArgs = arrayOf(calendarId.toString(), "%$VTOP_SYNC_FOOTPRINT%")
            val deletedCount = context.contentResolver.delete(CalendarContract.Events.CONTENT_URI, selection, selectionArgs)
            Toast.makeText(context, "Cleared $deletedCount synced events locally.", Toast.LENGTH_SHORT).show()
        } catch (e: Exception) {
            Toast.makeText(context, "Failed to clear events: ${e.localizedMessage}", Toast.LENGTH_SHORT).show()
        }
    }

    fun getDefaultEndDate(context: Context): String {
        val cache = parseBunkCache(context)
        if (cache.lastInstructionalDay.isNotEmpty()) {
            try {
                val jsonSdf = SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH)
                val uiSdf = SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH)
                val date = jsonSdf.parse(cache.lastInstructionalDay)
                if (date != null) return uiSdf.format(date)
            } catch (e: Exception) { }
        }

        val fallback = Calendar.getInstance().apply { add(Calendar.MONTH, 2) }
        return SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH).format(fallback.time)
    }

    @SuppressLint("SimpleDateFormat")
    fun syncToCalendar(
        context: Context,
        timetable: TimetableModel,
        exams: List<ExamScheduleModel>,
        mergeLabs: Boolean,
        calendarId: Long,
        reminderMinutes: Int,
        endDateString: String,
        titleTemplate: String,
        descTemplate: String,
        locTemplate: String
    ) {
        val resolver = context.contentResolver
        val timeFormat = SimpleDateFormat("HH:mm", Locale.ENGLISH)
        val timeFormatAmPm = SimpleDateFormat("hh:mm a", Locale.ENGLISH)

        val rruleUtcFormat = SimpleDateFormat("yyyyMMdd'T'HHmmss'Z'", Locale.ENGLISH).apply {
            timeZone = TimeZone.getTimeZone("UTC")
        }

        val dayMap = mapOf(
            "Monday" to Calendar.MONDAY, "Tuesday" to Calendar.TUESDAY, "Wednesday" to Calendar.WEDNESDAY,
            "Thursday" to Calendar.THURSDAY, "Friday" to Calendar.FRIDAY, "Saturday" to Calendar.SATURDAY, "Sunday" to Calendar.SUNDAY
        )

        try {
            val cacheData = parseBunkCache(context)
            scheduleExamCheckers(context, cacheData.examStartDates)

            var safeEndDateStr = ""
            try {
                val inputSdf = SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH)
                val parsedEnd = inputSdf.parse(endDateString)
                if (parsedEnd != null) {
                    val endCal = Calendar.getInstance().apply { time = parsedEnd }
                    endCal.set(Calendar.HOUR_OF_DAY, 23)
                    safeEndDateStr = rruleUtcFormat.format(endCal.time)
                }
            } catch (e: Exception) { }

            var classCount = 0
            var examCount = 0
            val currentTimeMs = System.currentTimeMillis()

            val colorBlue = android.graphics.Color.parseColor("#4285F4")
            val colorGreen = android.graphics.Color.parseColor("#34A853")
            val colorOrange = android.graphics.Color.parseColor("#F9AB00")

            // ==============================================
            // 1. SYNC WEEKLY TIMETABLE
            // ==============================================
            timetable.scheduleMap.forEach { (dayName, rawCourses) ->
                val dayOfWeek = dayMap[dayName] ?: return@forEach
                val courses = processAndMergeCourses(rawCourses, mergeLabs)

                courses.forEach { course ->
                    val times = course.mergedTimeSlot.split("-").map { it.trim() }
                    if (times.size < 2) return@forEach

                    val startCal = getNextOccurrenceOfDay(dayOfWeek)
                    val startTime = tryParseTime(times[0], timeFormat, timeFormatAmPm) ?: return@forEach
                    startCal.set(Calendar.HOUR_OF_DAY, startTime.hours)
                    startCal.set(Calendar.MINUTE, startTime.minutes)
                    startCal.set(Calendar.SECOND, 0)

                    val endCal = startCal.clone() as Calendar
                    val endTime = tryParseTime(times[1], timeFormat, timeFormatAmPm) ?: return@forEach
                    endCal.set(Calendar.HOUR_OF_DAY, endTime.hours)
                    endCal.set(Calendar.MINUTE, endTime.minutes)

                    val exdates = mutableListOf<String>()
                    cacheData.blockedDates.forEach { (blockedCal, _) ->
                        if (blockedCal.get(Calendar.DAY_OF_WEEK) == dayOfWeek) {
                            val exdateCal = blockedCal.clone() as Calendar
                            exdateCal.set(Calendar.HOUR_OF_DAY, startTime.hours)
                            exdateCal.set(Calendar.MINUTE, startTime.minutes)
                            exdateCal.set(Calendar.SECOND, 0)
                            exdates.add(rruleUtcFormat.format(exdateCal.time))
                        }
                    }

                    var rrule = "FREQ=WEEKLY;BYDAY=${dayName.take(2).uppercase(Locale.ENGLISH)}"
                    if (safeEndDateStr.isNotEmpty()) rrule += ";UNTIL=$safeEndDateStr"

                    val isLab = course.courseType?.contains("L", true) == true || course.courseType?.contains("P", true) == true
                    val eventColor = if (isLab) colorGreen else colorBlue

                    val parsedTitle = titleTemplate.replace("{courseCode}", course.courseCode.cleanStr()).replace("{courseType}", course.courseType.cleanStr()).replace("{slot}", course.mergedSlot).replace("{courseTitle}", course.courseName.cleanStr())
                    val parsedDesc = descTemplate.replace("{courseCode}", course.courseCode.cleanStr()).replace("{courseType}", course.courseType.cleanStr()).replace("{slot}", course.mergedSlot).replace("{faculty}", course.faculty.cleanStr()).replace("{courseTitle}", course.courseName.cleanStr()).replace("{classId}", course.classId.cleanStr()) + VTOP_SYNC_FOOTPRINT
                    val parsedLoc = locTemplate.replace("{venue}", course.venue.cleanStr()).replace("{seat}", "").replace("{classId}", course.classId.cleanStr()).trim().removePrefix("-").trim()

                    val values = ContentValues().apply {
                        put(CalendarContract.Events.DTSTART, startCal.timeInMillis)
                        put(CalendarContract.Events.DTEND, endCal.timeInMillis)
                        put(CalendarContract.Events.TITLE, parsedTitle)
                        put(CalendarContract.Events.DESCRIPTION, parsedDesc)
                        put(CalendarContract.Events.EVENT_LOCATION, parsedLoc)
                        put(CalendarContract.Events.CALENDAR_ID, calendarId)
                        put(CalendarContract.Events.EVENT_TIMEZONE, TimeZone.getDefault().id)
                        put(CalendarContract.Events.RRULE, rrule)
                        put(CalendarContract.Events.EVENT_COLOR, eventColor)
                        put(CalendarContract.Events.AVAILABILITY, CalendarContract.Events.AVAILABILITY_BUSY)
                        if (exdates.isNotEmpty()) put(CalendarContract.Events.EXDATE, exdates.joinToString(","))
                    }

                    val uri = resolver.insert(CalendarContract.Events.CONTENT_URI, values)
                    uri?.lastPathSegment?.toLongOrNull()?.let { eventId ->
                        if (reminderMinutes > 0) insertReminder(context, eventId, reminderMinutes)
                    }
                    classCount++
                }
            }

            // ==============================================
            // 2. SYNC ONE-TIME EXAMS
            // ==============================================
            val dateFormats = listOf("dd-MMM-yyyy", "yyyy-MM-dd", "dd/MM/yyyy", "dd-MM-yyyy", "MMM dd, yyyy")

            exams.forEach { exam ->
                val dateStr = exam.examDate.cleanStr()
                if (dateStr == " ") return@forEach
                val timeStr = (exam.examTime.takeIf { !it.isNullOrBlank() && it != "-" } ?: exam.reportingTime).cleanStr()
                if (timeStr == " ") return@forEach

                var parsedDate: Date? = null
                for (format in dateFormats) {
                    try { parsedDate = SimpleDateFormat(format, Locale.ENGLISH).parse(dateStr); if (parsedDate != null) break } catch (e: Exception) { }
                }
                if (parsedDate == null) return@forEach

                val times = timeStr.split("-").map { it.trim() }
                val startTime = tryParseTime(times[0], timeFormat, timeFormatAmPm) ?: return@forEach
                val endTime = if (times.size > 1) {
                    tryParseTime(times[1], timeFormat, timeFormatAmPm) ?: startTime
                } else {
                    val c = Calendar.getInstance().apply { time = startTime }
                    c.add(Calendar.HOUR_OF_DAY, 2)
                    c.time
                }

                val startCal = Calendar.getInstance().apply { time = parsedDate }
                startCal.set(Calendar.HOUR_OF_DAY, startTime.hours)
                startCal.set(Calendar.MINUTE, startTime.minutes)
                startCal.set(Calendar.SECOND, 0)

                val endCal = Calendar.getInstance().apply { time = parsedDate }
                endCal.set(Calendar.HOUR_OF_DAY, endTime.hours)
                endCal.set(Calendar.MINUTE, endTime.minutes)
                endCal.set(Calendar.SECOND, 0)

                if (endCal.timeInMillis < currentTimeMs) return@forEach

                val cleanVenue = exam.venue.cleanStr()
                val cleanLoc = exam.seatLocation.cleanStr()
                val cleanSeat = exam.seatNumber.cleanStr()
                val finalSeat = if (cleanLoc != " " && cleanSeat != " ") "$cleanLoc ($cleanSeat)" else if (cleanLoc != " ") cleanLoc else cleanSeat

                val parsedTitle = "[EXAM] " + titleTemplate.replace("{courseCode}", exam.courseCode.cleanStr()).replace("{courseType}", exam.examType.cleanStr()).replace("{slot}", exam.slot.cleanStr()).replace("{courseTitle}", exam.courseTitle.cleanStr())
                val parsedDesc = descTemplate.replace("{courseCode}", exam.courseCode.cleanStr()).replace("{courseType}", exam.examType.cleanStr()).replace("{slot}", exam.slot.cleanStr()).replace("{faculty}", "").replace("{courseTitle}", exam.courseTitle.cleanStr()).replace("{classId}", exam.classId.cleanStr()) + "\nSeat: $finalSeat" + VTOP_SYNC_FOOTPRINT
                val parsedLoc = locTemplate.replace("{venue}", cleanVenue).replace("{seat}", finalSeat).replace("{classId}", exam.classId.cleanStr()).trim().removePrefix("-").trim()

                val values = ContentValues().apply {
                    put(CalendarContract.Events.DTSTART, startCal.timeInMillis)
                    put(CalendarContract.Events.DTEND, endCal.timeInMillis)
                    put(CalendarContract.Events.TITLE, parsedTitle)
                    put(CalendarContract.Events.DESCRIPTION, parsedDesc)
                    put(CalendarContract.Events.EVENT_LOCATION, parsedLoc)
                    put(CalendarContract.Events.CALENDAR_ID, calendarId)
                    put(CalendarContract.Events.EVENT_TIMEZONE, TimeZone.getDefault().id)
                    put(CalendarContract.Events.EVENT_COLOR, colorOrange)
                    put(CalendarContract.Events.AVAILABILITY, CalendarContract.Events.AVAILABILITY_BUSY)
                }

                val uri = resolver.insert(CalendarContract.Events.CONTENT_URI, values)
                uri?.lastPathSegment?.toLongOrNull()?.let { eventId ->
                    if (reminderMinutes > 0) insertReminder(context, eventId, reminderMinutes)
                }
                examCount++
            }

            Toast.makeText(context, "Exported $classCount classes & $examCount exams.", Toast.LENGTH_LONG).show()
        } catch (e: Exception) {
            Toast.makeText(context, "Calendar Sync Failed: ${e.localizedMessage}", Toast.LENGTH_SHORT).show()
        }
    }

    private fun insertReminder(context: Context, eventId: Long, minutes: Int) {
        val reminderValues = ContentValues().apply {
            put(CalendarContract.Reminders.EVENT_ID, eventId)
            put(CalendarContract.Reminders.MINUTES, minutes)
            put(CalendarContract.Reminders.METHOD, CalendarContract.Reminders.METHOD_ALERT)
        }
        context.contentResolver.insert(CalendarContract.Reminders.CONTENT_URI, reminderValues)
    }

    fun parseBunkCache(context: Context): BunkCacheData {
        val blockedDates = mutableMapOf<Calendar, String>()
        val examStartDates = mutableMapOf<String, Calendar>()
        var lastDay = ""

        try {
            val jsonStr = context.assets.open("bunk_cache.json").bufferedReader().use { it.readText() }
            val root = JSONObject(jsonStr)

            if (root.has("semester")) {
                val semInfo = root.getJSONObject("semester")
                lastDay = semInfo.optString("last_instructional_day", "")
            }

            val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH)

            if (root.has("holidays")) {
                val holidays = root.getJSONObject("holidays")
                holidays.keys().forEach { dateStr ->
                    sdf.parse(dateStr)?.let { d ->
                        val cal = Calendar.getInstance().apply { time = d }
                        blockedDates[cal] = holidays.getString(dateStr)
                    }
                }
            }

            if (root.has("exams")) {
                val exams = root.getJSONObject("exams")
                exams.keys().forEach { examType ->
                    val datesArray = exams.getJSONArray(examType)
                    for (i in 0 until datesArray.length()) {
                        val dateStr = datesArray.getString(i)
                        sdf.parse(dateStr)?.let { d ->
                            val cal = Calendar.getInstance().apply { time = d }
                            blockedDates[cal] = "$examType Exam"
                            if (i == 0) examStartDates[examType] = cal
                        }
                    }
                }
            }
        } catch (e: Exception) { e.printStackTrace() }

        return BunkCacheData(lastDay, blockedDates, examStartDates)
    }

    private fun scheduleExamCheckers(context: Context, startDates: Map<String, Calendar>) {
        val workManager = WorkManager.getInstance(context)
        startDates.forEach { (examType, startCal) ->
            val triggerCal = startCal.clone() as Calendar
            triggerCal.add(Calendar.DAY_OF_YEAR, -2)
            triggerCal.set(Calendar.HOUR_OF_DAY, 9)
            triggerCal.set(Calendar.MINUTE, 0)

            val delayMillis = triggerCal.timeInMillis - System.currentTimeMillis()
            if (delayMillis > 0) {
                val inputData = Data.Builder().putString("EXAM_TYPE", examType).build()
                val workRequest = OneTimeWorkRequestBuilder<ExamCheckWorker>()
                    .setInitialDelay(delayMillis, TimeUnit.MILLISECONDS)
                    .setInputData(inputData)
                    .addTag("EXAM_CHECK_$examType")
                    .build()
                workManager.enqueue(workRequest)
            }
        }
    }

    private fun tryParseTime(timeStr: String, format24: SimpleDateFormat, format12: SimpleDateFormat): Date? {
        return try { if (timeStr.contains(Regex("[a-zA-Z]"))) format12.parse(timeStr) else format24.parse(timeStr) } catch (e: Exception) { null }
    }

    private fun getNextOccurrenceOfDay(dayOfWeek: Int): Calendar {
        val cal = Calendar.getInstance()
        while (cal.get(Calendar.DAY_OF_WEEK) != dayOfWeek) { cal.add(Calendar.DAY_OF_YEAR, 1) }
        return cal
    }
}