package com.vtop.sync

import android.annotation.SuppressLint
import android.content.ContentValues
import android.content.Context
import android.graphics.Color
import android.provider.CalendarContract
import android.widget.Toast
import com.vtop.models.ExamScheduleModel
import com.vtop.models.TimetableModel
import com.vtop.ui.screens.main.processAndMergeCourses
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale
import java.util.TimeZone

data class CalendarInfo(val id: Long, val name: String, val accountName: String)

data class BunkCacheData(
    val lastInstructionalDay: String,
    val blockedDates: Map<Calendar, String>,
    val examStartDates: Map<String, Calendar>
)

object CalendarSync {

    private const val VTOP_SYNC_FOOTPRINT = "\n\n[Generated by VTOP app]"

    private fun String?.cleanStr(): String {
        if (this.isNullOrBlank() || this.trim() == "-" || this.trim().equals("TBD", true) || this.trim().equals("N/A", true) || this.trim().equals("null", true)) {
            return " "
        }
        return this.trim()
    }

    private fun applyTemplate(
        template: String,
        values: Map<String, String>
    ): String {
        var result = template
        values.forEach { (key, value) ->
            result = result.replace("{$key}", value)
        }
        return result
    }

    @SuppressLint("Range")
    fun getWritableCalendars(context: Context): List<CalendarInfo> {
        val calendars = mutableListOf<CalendarInfo>()
        val projection = arrayOf(
            CalendarContract.Calendars._ID,
            CalendarContract.Calendars.CALENDAR_DISPLAY_NAME,
            CalendarContract.Calendars.ACCOUNT_NAME,
            CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL
        )
        val selection = "${CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL} >= ?"
        val selectionArgs = arrayOf(CalendarContract.Calendars.CAL_ACCESS_CONTRIBUTOR.toString())

        val cursor = context.contentResolver.query(CalendarContract.Calendars.CONTENT_URI, projection, selection, selectionArgs, null)
        cursor?.use {
            while (it.moveToNext()) {
                val id = it.getLong(it.getColumnIndex(CalendarContract.Calendars._ID))
                val name = it.getString(it.getColumnIndex(CalendarContract.Calendars.CALENDAR_DISPLAY_NAME)) ?: "Calendar"
                val account = it.getString(it.getColumnIndex(CalendarContract.Calendars.ACCOUNT_NAME)) ?: ""
                calendars.add(CalendarInfo(id, name, account))
            }
        }
        return calendars
    }

    fun clearSyncedEvents(context: Context, calendarId: Long) {
        try {
            val selection = "(${CalendarContract.Events.CALENDAR_ID} = ?) AND (${CalendarContract.Events.DESCRIPTION} LIKE ?)"
            val selectionArgs = arrayOf(calendarId.toString(), "%$VTOP_SYNC_FOOTPRINT%")
            val deletedCount = context.contentResolver.delete(CalendarContract.Events.CONTENT_URI, selection, selectionArgs)
            Toast.makeText(context, "Cleared $deletedCount synced events locally.", Toast.LENGTH_SHORT).show()
        } catch (_: Exception) {
            Toast.makeText(context, "Failed to clear events", Toast.LENGTH_SHORT).show()
        }
    }

    fun getDefaultEndDate(context: Context): String {
        val cache = parseBunkCache(context)
        if (cache.lastInstructionalDay.isNotEmpty()) {
            try {
                val jsonSdf = SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH)
                val uiSdf = SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH)
                val date = jsonSdf.parse(cache.lastInstructionalDay)
                if (date != null) return uiSdf.format(date)
            } catch (_: Exception) { }
        }

        val fallback = Calendar.getInstance().apply { add(Calendar.MONTH, 2) }
        return SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH).format(fallback.time)
    }

    fun parseBunkCache(context: Context): BunkCacheData {
        val blockedDates = mutableMapOf<Calendar, String>()
        val examStartDates = mutableMapOf<String, Calendar>()
        var lastDay = ""

        try {
            val semInfo = com.vtop.utils.Vault.getSelectedSemester(context)
            val semId = if (semInfo.isNotEmpty()) semInfo[0] else ""
            val events = com.vtop.utils.Vault.getAcademicCalendar(context, semId)

            val inputSdf = SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH)
            val outputSdf = SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH)
            var maxDate = Date(0)

            events.forEach { event ->
                val dateObj = inputSdf.parse(event.date) ?: return@forEach
                val cal = Calendar.getInstance().apply { time = dateObj }

                if (dateObj.after(maxDate)) {
                    maxDate = dateObj
                }

                val title = event.particulars.lowercase(Locale.ENGLISH)

                if (title.contains("holiday") || title.contains("festival") || title.contains("break") ||
                    title.contains("exam") || title.contains("cat") || title.contains("fat") ||
                    title.contains("no instructional") || title.contains("non instructional")
                ) {
                    blockedDates[cal] = event.particulars
                }

                if (title.contains("exam") || title.contains("cat") || title.contains("fat")) {
                    val examType = event.particulars
                    if (!examStartDates.containsKey(examType)) {
                        examStartDates[examType] = cal
                    }
                }
            }

            if (maxDate.time > 0) {
                lastDay = outputSdf.format(maxDate)
            }

        } catch (e: Exception) {
            e.printStackTrace()
        }

        return BunkCacheData(lastDay, blockedDates, examStartDates)
    }

    @SuppressLint("SimpleDateFormat")
    fun syncToCalendar(
        context: Context,
        timetable: TimetableModel,
        exams: List<ExamScheduleModel>,
        mergeLabs: Boolean,
        calendarId: Long,
        reminderMinutes: Int,
        endDateString: String,
        titleTemplate: String,
        descTemplate: String,
        locTemplate: String
    ) {
        val resolver = context.contentResolver
        val timeFormat = SimpleDateFormat("HH:mm", Locale.ENGLISH)
        val timeFormatAmPm = SimpleDateFormat("hh:mm a", Locale.ENGLISH)

        val rruleUtcFormat = SimpleDateFormat("yyyyMMdd'T'HHmmss'Z'", Locale.ENGLISH).apply {
            timeZone = TimeZone.getTimeZone("UTC")
        }

        val dayMap = mapOf(
            "Monday" to Calendar.MONDAY, "Tuesday" to Calendar.TUESDAY, "Wednesday" to Calendar.WEDNESDAY,
            "Thursday" to Calendar.THURSDAY, "Friday" to Calendar.FRIDAY, "Saturday" to Calendar.SATURDAY, "Sunday" to Calendar.SUNDAY
        )

        try {
            val cacheData = parseBunkCache(context)

            var safeEndDateStr = ""
            try {
                val inputSdf = SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH)
                val parsedEnd = inputSdf.parse(endDateString)
                if (parsedEnd != null) {
                    val endCal = Calendar.getInstance().apply { time = parsedEnd }
                    endCal.set(Calendar.HOUR_OF_DAY, 23)
                    safeEndDateStr = rruleUtcFormat.format(endCal.time)
                }
            } catch (_: Exception) { }

            var classCount = 0
            var examCount = 0
            val currentTimeMs = System.currentTimeMillis()

            val colorBlue = Color.parseColor("#4285F4")
            val colorGreen = Color.parseColor("#34A853")
            val colorOrange = Color.parseColor("#F9AB00")

            // ==============================================
            // 1. SYNC WEEKLY TIMETABLE
            // ==============================================
            timetable.scheduleMap.forEach { (dayName, rawCourses) ->
                val dayOfWeek = dayMap[dayName] ?: return@forEach
                val courses = processAndMergeCourses(rawCourses, mergeLabs)

                courses.forEach { course ->
                    val times = course.mergedTimeSlot.split("-").map { it.trim() }
                    if (times.size < 2) return@forEach

                    val startCal = getNextOccurrenceOfDay(dayOfWeek)
                    val parsedStartTime = tryParseTime(times[0], timeFormat, timeFormatAmPm) ?: return@forEach

                    val timeHelperCal = Calendar.getInstance().apply { time = parsedStartTime }
                    val startHour = timeHelperCal.get(Calendar.HOUR_OF_DAY)
                    val startMinute = timeHelperCal.get(Calendar.MINUTE)

                    startCal.set(Calendar.HOUR_OF_DAY, startHour)
                    startCal.set(Calendar.MINUTE, startMinute)
                    startCal.set(Calendar.SECOND, 0)

                    val endCal = startCal.clone() as Calendar
                    val parsedEndTime = tryParseTime(times[1], timeFormat, timeFormatAmPm) ?: return@forEach
                    timeHelperCal.time = parsedEndTime
                    endCal.set(Calendar.HOUR_OF_DAY, timeHelperCal.get(Calendar.HOUR_OF_DAY))
                    endCal.set(Calendar.MINUTE, timeHelperCal.get(Calendar.MINUTE))

                    val exdates = mutableListOf<String>()
                    cacheData.blockedDates.forEach { (blockedCal, _) ->
                        if (blockedCal.get(Calendar.DAY_OF_WEEK) == dayOfWeek) {
                            val exdateCal = blockedCal.clone() as Calendar
                            exdateCal.set(Calendar.HOUR_OF_DAY, startHour)
                            exdateCal.set(Calendar.MINUTE, startMinute)
                            exdateCal.set(Calendar.SECOND, 0)
                            exdates.add(rruleUtcFormat.format(exdateCal.time))
                        }
                    }

                    exams.forEach { exam ->
                        val formats = listOf("dd-MMM-yyyy", "yyyy-MM-dd", "dd/MM/yyyy", "dd-MM-yyyy")
                        for (f in formats) {
                            try {
                                val d = SimpleDateFormat(f, Locale.ENGLISH).parse(exam.examDate.cleanStr())
                                if (d != null) {
                                    val checkCal = Calendar.getInstance().apply { time = d }
                                    if (checkCal.get(Calendar.DAY_OF_WEEK) == dayOfWeek) {
                                        checkCal.set(Calendar.HOUR_OF_DAY, startHour)
                                        checkCal.set(Calendar.MINUTE, startMinute)
                                        checkCal.set(Calendar.SECOND, 0)
                                        exdates.add(rruleUtcFormat.format(checkCal.time))
                                    }
                                    break
                                }
                            } catch (_: Exception) {}
                        }
                    }

                    var rrule = "FREQ=WEEKLY;BYDAY=${dayName.take(2).uppercase(Locale.ENGLISH)}"
                    if (safeEndDateStr.isNotEmpty()) rrule += ";UNTIL=$safeEndDateStr"

                    val isLab = course.courseType?.contains("L", true) == true || course.courseType?.contains("P", true) == true
                    val eventColor = if (isLab) colorGreen else colorBlue

                    val templateValues = mapOf(
                        "courseCode" to course.courseCode.cleanStr(),
                        "courseType" to course.courseType.cleanStr(),
                        "slot" to course.mergedSlot,
                        "courseTitle" to course.courseName.cleanStr(),
                        "faculty" to course.faculty.cleanStr(),
                        "classId" to course.classId.cleanStr(),
                        "venue" to course.venue.cleanStr(),
                        "seat" to ""
                    )

                    val parsedTitle = applyTemplate(titleTemplate, templateValues)
                    val parsedDesc = applyTemplate(descTemplate, templateValues) + VTOP_SYNC_FOOTPRINT
                    val parsedLoc = applyTemplate(locTemplate, templateValues).trim().removePrefix("-").trim()

                    val values = ContentValues().apply {
                        put(CalendarContract.Events.DTSTART, startCal.timeInMillis)
                        put(CalendarContract.Events.DTEND, endCal.timeInMillis)
                        put(CalendarContract.Events.TITLE, parsedTitle)
                        put(CalendarContract.Events.DESCRIPTION, parsedDesc)
                        put(CalendarContract.Events.EVENT_LOCATION, parsedLoc)
                        put(CalendarContract.Events.CALENDAR_ID, calendarId)
                        put(CalendarContract.Events.EVENT_TIMEZONE, TimeZone.getDefault().id)
                        put(CalendarContract.Events.RRULE, rrule)
                        put(CalendarContract.Events.EVENT_COLOR, eventColor)
                        put(CalendarContract.Events.AVAILABILITY, CalendarContract.Events.AVAILABILITY_BUSY)
                        if (exdates.isNotEmpty()) put(CalendarContract.Events.EXDATE, exdates.joinToString(","))
                    }

                    val uri = resolver.insert(CalendarContract.Events.CONTENT_URI, values)
                    uri?.lastPathSegment?.toLongOrNull()?.let { eventId ->
                        if (reminderMinutes > 0) insertReminder(context, eventId, reminderMinutes)
                    }
                    classCount++
                }
            }

            // ==============================================
            // 2. SYNC ONE-TIME EXAMS
            // ==============================================
            val dateFormats = listOf("dd-MMM-yyyy", "yyyy-MM-dd", "dd/MM/yyyy", "dd-MM-yyyy", "MMM dd, yyyy")

            exams.forEach { exam ->
                val dateStr = exam.examDate.cleanStr()
                if (dateStr == " ") return@forEach
                val timeStr = (exam.examTime.takeIf { !it.isNullOrBlank() && it != "-" } ?: exam.reportingTime).cleanStr()
                if (timeStr == " ") return@forEach

                var parsedDate: Date? = null
                for (format in dateFormats) {
                    try { parsedDate = SimpleDateFormat(format, Locale.ENGLISH).parse(dateStr); if (parsedDate != null) break } catch (_: Exception) { }
                }
                if (parsedDate == null) return@forEach

                val times = timeStr.split("-").map { it.trim() }
                val parsedStartTime = tryParseTime(times[0], timeFormat, timeFormatAmPm) ?: return@forEach

                val timeHelperCal = Calendar.getInstance().apply { time = parsedStartTime }

                val startCal = Calendar.getInstance().apply { time = parsedDate }
                startCal.set(Calendar.HOUR_OF_DAY, timeHelperCal.get(Calendar.HOUR_OF_DAY))
                startCal.set(Calendar.MINUTE, timeHelperCal.get(Calendar.MINUTE))
                startCal.set(Calendar.SECOND, 0)

                val endCal = Calendar.getInstance().apply { time = parsedDate }
                val parsedEndTime = if (times.size > 1) {
                    tryParseTime(times[1], timeFormat, timeFormatAmPm) ?: parsedStartTime
                } else {
                    val c = Calendar.getInstance().apply { time = parsedStartTime }
                    c.add(Calendar.HOUR_OF_DAY, 2)
                    c.time
                }
                timeHelperCal.time = parsedEndTime
                endCal.set(Calendar.HOUR_OF_DAY, timeHelperCal.get(Calendar.HOUR_OF_DAY))
                endCal.set(Calendar.MINUTE, timeHelperCal.get(Calendar.MINUTE))
                endCal.set(Calendar.SECOND, 0)

                if (endCal.timeInMillis < currentTimeMs) return@forEach

                val cleanVenue = exam.venue.cleanStr().trim()
                val cleanLoc = exam.seatLocation.cleanStr().trim()
                val cleanSeat = exam.seatNumber.cleanStr().trim()
                val cleanSlot = exam.slot.cleanStr().trim()

                // Generate specific seat suffix for Title
                val seatTitlePart = if (cleanLoc.isNotBlank() && cleanSeat.isNotBlank()) {
                    "-$cleanLoc ($cleanSeat)"
                } else if (cleanLoc.isNotBlank()) {
                    "-$cleanLoc"
                } else if (cleanSeat.isNotBlank()) {
                    " ($cleanSeat)"
                } else ""

                // Ensure format is always CAT-1 or CAT-2
                val cleanExamType = exam.examType.cleanStr()
                    .replace(Regex("CAT\\s*1", RegexOption.IGNORE_CASE), "CAT-1")
                    .replace(Regex("CAT\\s*2", RegexOption.IGNORE_CASE), "CAT-2")

                val venuePart = if (cleanVenue.isNotBlank()) "- $cleanVenue" else ""

                // Final Title: CSE3003- F1- CAT-1- CB-520-Row A (12)
                val parsedTitle = "${exam.courseCode.cleanStr()}- $cleanSlot- $cleanExamType$venuePart$seatTitlePart"

                // Extract Faculty from Weekly Timetable
                var faculty = "Not Assigned"
                for (dayList in timetable.scheduleMap.values) {
                    val found = dayList.find { it.courseCode.cleanStr() == exam.courseCode.cleanStr() }
                    if (found != null) {
                        faculty = found.faculty.cleanStr()
                        break
                    }
                }

                val finalSeatDesc = if (cleanLoc.isNotBlank() && cleanSeat.isNotBlank()) "$cleanLoc ($cleanSeat)" else if (cleanLoc.isNotBlank()) cleanLoc else cleanSeat

                // Match exact structure from the reference image
                val parsedDesc = "${exam.courseTitle.cleanStr()}\nFaculty: $faculty\nType: $cleanExamType\nClass ID: ${exam.classId.cleanStr()}\nVenue: $cleanVenue\nSeat: $finalSeatDesc$VTOP_SYNC_FOOTPRINT"

                val parsedLoc = cleanVenue

                val values = ContentValues().apply {
                    put(CalendarContract.Events.DTSTART, startCal.timeInMillis)
                    put(CalendarContract.Events.DTEND, endCal.timeInMillis)
                    put(CalendarContract.Events.TITLE, parsedTitle)
                    put(CalendarContract.Events.DESCRIPTION, parsedDesc)
                    put(CalendarContract.Events.EVENT_LOCATION, parsedLoc)
                    put(CalendarContract.Events.CALENDAR_ID, calendarId)
                    put(CalendarContract.Events.EVENT_TIMEZONE, TimeZone.getDefault().id)
                    put(CalendarContract.Events.EVENT_COLOR, colorOrange)
                    put(CalendarContract.Events.AVAILABILITY, CalendarContract.Events.AVAILABILITY_BUSY)
                }

                val uri = resolver.insert(CalendarContract.Events.CONTENT_URI, values)
                uri?.lastPathSegment?.toLongOrNull()?.let { eventId ->
                    insertReminder(context, eventId, 30) // Hardcoded 30 minutes explicitly for Exams
                }
                examCount++
            }

            Toast.makeText(context, "Exported $classCount classes & $examCount exams.", Toast.LENGTH_LONG).show()
        } catch (e: Exception) {
            Toast.makeText(context, "Calendar Sync Failed: ${e.localizedMessage}", Toast.LENGTH_SHORT).show()
        }
    }

    private fun insertReminder(context: Context, eventId: Long, minutes: Int) {
        val reminderValues = ContentValues().apply {
            put(CalendarContract.Reminders.EVENT_ID, eventId)
            put(CalendarContract.Reminders.MINUTES, minutes)
            put(CalendarContract.Reminders.METHOD, CalendarContract.Reminders.METHOD_ALERT)
        }
        context.contentResolver.insert(CalendarContract.Reminders.CONTENT_URI, reminderValues)
    }

    private fun tryParseTime(timeStr: String, format24: SimpleDateFormat, format12: SimpleDateFormat): Date? {
        return try { if (timeStr.contains(Regex("[a-zA-Z]"))) format12.parse(timeStr) else format24.parse(timeStr) } catch (_: Exception) { null }
    }

    private fun getNextOccurrenceOfDay(dayOfWeek: Int): Calendar {
        val cal = Calendar.getInstance()
        while (cal.get(Calendar.DAY_OF_WEEK) != dayOfWeek) { cal.add(Calendar.DAY_OF_YEAR, 1) }
        return cal
    }
}