package com.vtop.sync

import android.annotation.SuppressLint
import android.content.ContentValues
import android.content.Context
import android.graphics.Color
import android.provider.CalendarContract
import android.widget.Toast
import android.content.ContentProviderOperation
import android.content.ContentUris
import com.vtop.models.ExamScheduleModel
import com.vtop.models.TimetableModel
import com.vtop.ui.screens.main.processAndMergeCourses
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale
import java.util.TimeZone

data class CalendarInfo(val id: Long, val name: String, val accountName: String)

data class BunkCacheData(
    val lastInstructionalDay: String,
    val blockedDates: Map<Calendar, String>,
    val examStartDates: Map<String, Calendar>
)

object CalendarSync {

    private const val VTOP_SYNC_FOOTPRINT = "[Generated by VTOP app]"

    private fun String?.cleanStr(): String {
        if (this.isNullOrBlank() || this.trim() == "-" || this.trim().equals("TBD", true) || this.trim().equals("N/A", true) || this.trim().equals("null", true)) {
            return " "
        }
        return this.trim()
    }

    private fun applyTemplate(
        template: String,
        values: Map<String, String>
    ): String {
        var result = template
        values.forEach { (key, value) ->
            result = result.replace("{$key}", value)
        }
        return result
    }

    @SuppressLint("Range")
    fun getWritableCalendars(context: Context): List<CalendarInfo> {
        val calendars = mutableListOf<CalendarInfo>()
        val projection = arrayOf(
            CalendarContract.Calendars._ID,
            CalendarContract.Calendars.CALENDAR_DISPLAY_NAME,
            CalendarContract.Calendars.ACCOUNT_NAME,
            CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL
        )
        val selection = "${CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL} >= ?"
        val selectionArgs = arrayOf(CalendarContract.Calendars.CAL_ACCESS_CONTRIBUTOR.toString())

        val cursor = context.contentResolver.query(CalendarContract.Calendars.CONTENT_URI, projection, selection, selectionArgs, null)
        cursor?.use {
            while (it.moveToNext()) {
                val id = it.getLong(it.getColumnIndex(CalendarContract.Calendars._ID))
                val name = it.getString(it.getColumnIndex(CalendarContract.Calendars.CALENDAR_DISPLAY_NAME)) ?: "Calendar"
                val account = it.getString(it.getColumnIndex(CalendarContract.Calendars.ACCOUNT_NAME)) ?: ""
                calendars.add(CalendarInfo(id, name, account))
            }
        }
        return calendars
    }

    fun clearSyncedEvents(context: Context, calendarId: Long) {
        try {
            val syncUri = getSyncAdapterUri(context, calendarId)
            val selection = "(${CalendarContract.Events.CALENDAR_ID} = ?) AND (${CalendarContract.Events.DESCRIPTION} LIKE ?)"
            val selectionArgs = arrayOf(calendarId.toString(), "%$VTOP_SYNC_FOOTPRINT%")
            val deletedCount = context.contentResolver.delete(syncUri, selection, selectionArgs)
            Toast.makeText(context, "Cleared $deletedCount synced events locally.", Toast.LENGTH_SHORT).show()
        } catch (_: Exception) {
            Toast.makeText(context, "Failed to clear events", Toast.LENGTH_SHORT).show()
        }
    }

    fun getDefaultEndDate(context: Context): String {
        val cache = parseAcademicTimeline(context)
        if (cache.lastInstructionalDay.isNotEmpty()) {
            try {
                val jsonSdf = SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH)
                val uiSdf = SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH)
                val date = jsonSdf.parse(cache.lastInstructionalDay)
                if (date != null) return uiSdf.format(date)
            } catch (_: Exception) { }
        }

        val fallback = Calendar.getInstance().apply { add(Calendar.MONTH, 2) }
        return SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH).format(fallback.time)
    }

    fun parseAcademicTimeline(context: Context): BunkCacheData {
        val blockedDates = mutableMapOf<Calendar, String>()
        val examStartDates = mutableMapOf<String, Calendar>()
        var lastDay = ""
        var explicitLastInstructionalDay: Date? = null
        var earliestFatDate: Date? = null

        try {
            val semInfo = com.vtop.utils.Vault.getSelectedSemester(context)
            val semId = if (semInfo.isNotEmpty()) semInfo[0] else ""
            val events = com.vtop.utils.Vault.getAcademicCalendar(context, semId)

            val inputSdf = SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH)
            val outputSdf = SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH)

            events.forEach { event ->
                val dateObj = inputSdf.parse(event.date) ?: return@forEach
                val cal = Calendar.getInstance().apply { time = dateObj }

                val title = event.particulars.lowercase(Locale.ENGLISH)

                // Exclude LAB FAT from blocked dates so normal classes continue to sync
                if (!title.contains("lab fat") && (
                            title.contains("holiday") || title.contains("festival") || title.contains("break") ||
                                    title.contains("exam") || title.contains("cat") || title.contains("fat") ||
                                    title.contains("no instructional") || title.contains("non instructional")
                            )) {
                    blockedDates[cal] = event.particulars
                }

                if (title.contains("exam") || title.contains("cat") || title.contains("fat")) {
                    val examType = event.particulars
                    if (!examStartDates.containsKey(examType)) {
                        examStartDates[examType] = cal
                    }
                }

                // [OPTION A]: Look for an explicit "Last Instructional Day" mention
                if (title.contains("last instructional day")) {
                    explicitLastInstructionalDay = dateObj
                }
                // Track the earliest FAT date for Option B fallback (ignoring Lab FATs)
                if (title.contains("final assessment") || (title.contains("fat") && !title.contains("lab fat"))) {
                    if (earliestFatDate == null || dateObj.before(earliestFatDate)) {
                        earliestFatDate = dateObj
                    }
                }
            }

            // Calculation of the date of last instructional day
            if (explicitLastInstructionalDay != null) {
                lastDay = outputSdf.format(explicitLastInstructionalDay!!)
            } else if (earliestFatDate != null) {
                // [OPTION B]: Step backward from FAT to find the last valid working day
                val cal = Calendar.getInstance().apply { time = earliestFatDate!! }
                cal.add(Calendar.DAY_OF_YEAR, -1)

                var foundInstructionalDay = false
                while (!foundInstructionalDay) {
                    val isSunday = cal.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY

                    val isBlocked = blockedDates.keys.any {
                        it.get(Calendar.YEAR) == cal.get(Calendar.YEAR) &&
                                it.get(Calendar.DAY_OF_YEAR) == cal.get(Calendar.DAY_OF_YEAR)
                    }

                    if (!isSunday && !isBlocked) {
                        foundInstructionalDay = true
                    } else {
                        cal.add(Calendar.DAY_OF_YEAR, -1)
                    }
                }
                lastDay = outputSdf.format(cal.time)
            }

        } catch (e: Exception) {
            e.printStackTrace()
        }

        return BunkCacheData(lastDay, blockedDates, examStartDates)
    }

    private fun getSyncAdapterUri(context: Context, calendarId: Long): android.net.Uri {
        var uri = CalendarContract.Events.CONTENT_URI
        try {
            context.contentResolver.query(
                CalendarContract.Calendars.CONTENT_URI,
                arrayOf(CalendarContract.Calendars.ACCOUNT_NAME, CalendarContract.Calendars.ACCOUNT_TYPE),
                "${CalendarContract.Calendars._ID} = ?",
                arrayOf(calendarId.toString()),
                null
            )?.use { cursor ->
                if (cursor.moveToFirst()) {
                    uri = uri.buildUpon()
                        .appendQueryParameter(CalendarContract.CALLER_IS_SYNCADAPTER, "true")
                        .appendQueryParameter(CalendarContract.Calendars.ACCOUNT_NAME, cursor.getString(0))
                        .appendQueryParameter(CalendarContract.Calendars.ACCOUNT_TYPE, cursor.getString(1))
                        .build()
                }
            }
        } catch (_: Exception) {}
        return uri
    }

    @SuppressLint("SimpleDateFormat")
    fun syncToCalendar(
        context: Context,
        timetable: TimetableModel,
        exams: List<ExamScheduleModel>,
        mergeLabs: Boolean,
        calendarId: Long,
        reminderMinutes: Int,
        endDateString: String,
        titleTemplate: String,
        descTemplate: String,
        locTemplate: String
    ) {
        val resolver = context.contentResolver

        val rruleUtcFormat = SimpleDateFormat("yyyyMMdd'T'HHmmss'Z'", Locale.ENGLISH).apply {
            timeZone = TimeZone.getTimeZone("UTC")
        }

        val dayMap = mapOf(
            "Monday" to Calendar.MONDAY, "Tuesday" to Calendar.TUESDAY, "Wednesday" to Calendar.WEDNESDAY,
            "Thursday" to Calendar.THURSDAY, "Friday" to Calendar.FRIDAY, "Saturday" to Calendar.SATURDAY, "Sunday" to Calendar.SUNDAY
        )

        try {
            val cacheData = parseAcademicTimeline(context)

            var safeEndDateStr = ""
            try {
                val inputSdf = SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH)
                val parsedEnd = inputSdf.parse(endDateString)
                if (parsedEnd != null) {
                    val endCal = Calendar.getInstance().apply { time = parsedEnd }
                    endCal.set(Calendar.HOUR_OF_DAY, 23)
                    safeEndDateStr = rruleUtcFormat.format(endCal.time)
                }
            } catch (_: Exception) { }

            val currentTimeMs = System.currentTimeMillis()
            val colorBlue = Color.parseColor("#4285F4")
            val colorGreen = Color.parseColor("#34A853")
            val colorOrange = Color.parseColor("#F9AB00")

            // Map to hold all our newly generated target events
            val targetEvents = mutableMapOf<String, ContentValues>()

            // 1. GENERATE WEEKLY TIMETABLE VALUES
            timetable.scheduleMap.forEach { (dayName, rawCourses) ->
                val dayOfWeek = dayMap[dayName] ?: return@forEach
                val courses = processAndMergeCourses(rawCourses, mergeLabs)

                courses.forEach { course ->
                    val times = course.mergedTimeSlot.split("-").map { it.trim() }
                    if (times.size < 2) return@forEach

                    val startCal = getNextOccurrenceOfDay(dayOfWeek)
                    val parsedStartTime = tryParseTime(times[0]) ?: return@forEach
                    val timeHelperCal = Calendar.getInstance().apply { time = parsedStartTime }
                    val startHour = timeHelperCal.get(Calendar.HOUR_OF_DAY)
                    val startMinute = timeHelperCal.get(Calendar.MINUTE)

                    startCal.set(Calendar.HOUR_OF_DAY, startHour)
                    startCal.set(Calendar.MINUTE, startMinute)
                    startCal.set(Calendar.SECOND, 0)

                    val endCal = startCal.clone() as Calendar
                    val parsedEndTime = tryParseTime(times[1]) ?: return@forEach
                    timeHelperCal.time = parsedEndTime
                    endCal.set(Calendar.HOUR_OF_DAY, timeHelperCal.get(Calendar.HOUR_OF_DAY))
                    endCal.set(Calendar.MINUTE, timeHelperCal.get(Calendar.MINUTE))

                    val exdates = mutableListOf<String>()
                    cacheData.blockedDates.forEach { (blockedCal, _) ->
                        if (blockedCal.get(Calendar.DAY_OF_WEEK) == dayOfWeek) {
                            val exdateCal = blockedCal.clone() as Calendar
                            exdateCal.set(Calendar.HOUR_OF_DAY, startHour)
                            exdateCal.set(Calendar.MINUTE, startMinute)
                            exdateCal.set(Calendar.SECOND, 0)
                            exdates.add(rruleUtcFormat.format(exdateCal.time))
                        }
                    }

                    exams.forEach { exam ->
                        val formats = listOf("dd-MMM-yyyy", "yyyy-MM-dd", "dd/MM/yyyy", "dd-MM-yyyy")
                        for (f in formats) {
                            try {
                                val d = SimpleDateFormat(f, Locale.ENGLISH).parse(exam.examDate.cleanStr())
                                if (d != null) {
                                    val checkCal = Calendar.getInstance().apply { time = d }
                                    if (checkCal.get(Calendar.DAY_OF_WEEK) == dayOfWeek) {
                                        checkCal.set(Calendar.HOUR_OF_DAY, startHour)
                                        checkCal.set(Calendar.MINUTE, startMinute)
                                        checkCal.set(Calendar.SECOND, 0)
                                        exdates.add(rruleUtcFormat.format(checkCal.time))
                                    }
                                    break
                                }
                            } catch (_: Exception) {}
                        }
                    }

                    var rrule = "FREQ=WEEKLY;BYDAY=${dayName.take(2).uppercase(Locale.ENGLISH)}"
                    if (safeEndDateStr.isNotEmpty()) rrule += ";UNTIL=$safeEndDateStr"

                    val isLab = course.courseType?.contains("L", true) == true || course.courseType?.contains("P", true) == true
                    val eventColor = if (isLab) colorGreen else colorBlue

                    val templateValues = mapOf(
                        "courseCode" to course.courseCode.cleanStr(),
                        "courseType" to course.courseType.cleanStr(),
                        "slot" to course.mergedSlot,
                        "courseTitle" to course.courseName.cleanStr(),
                        "faculty" to course.faculty.cleanStr(),
                        "classId" to course.classId.cleanStr(),
                        "venue" to course.venue.cleanStr(),
                        "seat" to ""
                    )

                    val vtopId = "CLASS_${course.courseCode.cleanStr()}_${course.mergedSlot}_${dayName.uppercase(Locale.ENGLISH)}"
                    val parsedTitle = applyTemplate(titleTemplate, templateValues)
                    val parsedDesc = applyTemplate(descTemplate, templateValues) + "\n\n$VTOP_SYNC_FOOTPRINT\n[VTOP_ID: $vtopId]"
                    val parsedLoc = applyTemplate(locTemplate, templateValues).trim().removePrefix("-").trim()

                    val values = ContentValues().apply {
                        put(CalendarContract.Events.DTSTART, startCal.timeInMillis)

                        val durationSeconds = (endCal.timeInMillis - startCal.timeInMillis) / 1000
                        put(CalendarContract.Events.DURATION, "P${durationSeconds}S")
                        putNull(CalendarContract.Events.DTEND)
                        put(CalendarContract.Events.TITLE, parsedTitle)
                        put(CalendarContract.Events.DESCRIPTION, parsedDesc)
                        put(CalendarContract.Events.EVENT_LOCATION, parsedLoc)
                        put(CalendarContract.Events.CALENDAR_ID, calendarId)
                        put(CalendarContract.Events.EVENT_TIMEZONE, "Asia/Kolkata")
                        put(CalendarContract.Events.RRULE, rrule)
                        put(CalendarContract.Events.EVENT_COLOR, eventColor)
                        put(CalendarContract.Events.AVAILABILITY, CalendarContract.Events.AVAILABILITY_BUSY)
                        if (exdates.isNotEmpty()) put(CalendarContract.Events.EXDATE, exdates.joinToString(","))
                    }

                    targetEvents[vtopId] = values
                }
            }

            // 2. GENERATE ONE-TIME EXAMS VALUES
            val dateFormats = listOf("dd-MMM-yyyy", "yyyy-MM-dd", "dd/MM/yyyy", "dd-MM-yyyy", "MMM dd, yyyy")

            exams.forEach { exam ->
                val dateStr = exam.examDate.cleanStr()
                if (dateStr == " ") return@forEach
                val timeStr = (exam.examTime.takeIf { !it.isNullOrBlank() && it != "-" } ?: exam.reportingTime).cleanStr()
                if (timeStr == " ") return@forEach

                var parsedDate: Date? = null
                for (format in dateFormats) {
                    try { parsedDate = SimpleDateFormat(format, Locale.ENGLISH).parse(dateStr); if (parsedDate != null) break } catch (_: Exception) { }
                }
                if (parsedDate == null) return@forEach

                val times = timeStr.split("-").map { it.trim() }
                val parsedStartTime = tryParseTime(times[0]) ?: return@forEach

                val timeHelperCal = Calendar.getInstance().apply { time = parsedStartTime }
                val startCal = Calendar.getInstance().apply { time = parsedDate }
                startCal.set(Calendar.HOUR_OF_DAY, timeHelperCal.get(Calendar.HOUR_OF_DAY))
                startCal.set(Calendar.MINUTE, timeHelperCal.get(Calendar.MINUTE))
                startCal.set(Calendar.SECOND, 0)

                val endCal = Calendar.getInstance().apply { time = parsedDate }
                val parsedEndTime = if (times.size > 1) {
                    tryParseTime(times[1]) ?: parsedStartTime
                } else {
                    val c = Calendar.getInstance().apply { time = parsedStartTime }
                    c.add(Calendar.HOUR_OF_DAY, 2)
                    c.time
                }
                timeHelperCal.time = parsedEndTime
                endCal.set(Calendar.HOUR_OF_DAY, timeHelperCal.get(Calendar.HOUR_OF_DAY))
                endCal.set(Calendar.MINUTE, timeHelperCal.get(Calendar.MINUTE))
                endCal.set(Calendar.SECOND, 0)

                if (endCal.timeInMillis < currentTimeMs) return@forEach

                val cleanVenue = exam.venue.cleanStr().trim()
                val cleanLoc = exam.seatLocation.cleanStr().trim()
                val cleanSeat = exam.seatNumber.cleanStr().trim()
                val cleanSlot = exam.slot.cleanStr().trim()
                val seatTitlePart = if (cleanLoc.isNotBlank() && cleanSeat.isNotBlank()) "-$cleanLoc ($cleanSeat)" else if (cleanLoc.isNotBlank()) "-$cleanLoc" else if (cleanSeat.isNotBlank()) " ($cleanSeat)" else ""
                val cleanExamType = exam.examType.cleanStr().replace(Regex("CAT\\s*1", RegexOption.IGNORE_CASE), "CAT-1").replace(Regex("CAT\\s*2", RegexOption.IGNORE_CASE), "CAT-2")
                val venuePart = if (cleanVenue.isNotBlank()) "- $cleanVenue" else ""

                val vtopId = "EXAM_${exam.courseCode.cleanStr()}_$cleanExamType"
                val parsedTitle = "${exam.courseCode.cleanStr()}- $cleanSlot- $cleanExamType$venuePart$seatTitlePart"

                var faculty = "Not Assigned"
                for (dayList in timetable.scheduleMap.values) {
                    val found = dayList.find { it.courseCode.cleanStr() == exam.courseCode.cleanStr() }
                    if (found != null) { faculty = found.faculty.cleanStr(); break }
                }

                val finalSeatDesc = if (cleanLoc.isNotBlank() && cleanSeat.isNotBlank()) "$cleanLoc ($cleanSeat)" else if (cleanLoc.isNotBlank()) cleanLoc else cleanSeat
                val parsedDesc = "${exam.courseTitle.cleanStr()}\nFaculty: $faculty\nType: $cleanExamType\nClass ID: ${exam.classId.cleanStr()}\nVenue: $cleanVenue\nSeat: $finalSeatDesc$VTOP_SYNC_FOOTPRINT\n[VTOP_ID: $vtopId]"
                val parsedLoc = cleanVenue

                val values = ContentValues().apply {
                    put(CalendarContract.Events.DTSTART, startCal.timeInMillis)
                    put(CalendarContract.Events.DTEND, endCal.timeInMillis)
                    put(CalendarContract.Events.TITLE, parsedTitle)
                    put(CalendarContract.Events.DESCRIPTION, parsedDesc)
                    put(CalendarContract.Events.EVENT_LOCATION, parsedLoc)
                    put(CalendarContract.Events.CALENDAR_ID, calendarId)
                    put(CalendarContract.Events.EVENT_TIMEZONE, "Asia/Kolkata")
                    put(CalendarContract.Events.EVENT_COLOR, colorOrange)
                    put(CalendarContract.Events.AVAILABILITY, CalendarContract.Events.AVAILABILITY_BUSY)
                }

                targetEvents[vtopId] = values
            }

            // ==============================================
            // 3. GENERATE ACADEMIC CALENDAR EVENTS
            // ==============================================
            cacheData.blockedDates.forEach { (blockedCal, eventName) ->
                if (blockedCal.timeInMillis > currentTimeMs - (2 * 86400000L)) {
                    val startOfDayUtc = Calendar.getInstance(TimeZone.getTimeZone("UTC")).apply {
                        set(Calendar.YEAR, blockedCal.get(Calendar.YEAR))
                        set(Calendar.DAY_OF_YEAR, blockedCal.get(Calendar.DAY_OF_YEAR))
                        set(Calendar.HOUR_OF_DAY, 0); set(Calendar.MINUTE, 0); set(Calendar.SECOND, 0); set(Calendar.MILLISECOND, 0)
                    }

                    val endOfDayUtc = startOfDayUtc.clone() as Calendar
                    endOfDayUtc.add(Calendar.DAY_OF_YEAR, 1)
                    val cleanTitle = Regex("\\((.*?)\\)").find(eventName)?.groupValues?.get(1) ?: eventName
                    val vtopId = "HOLIDAY_${startOfDayUtc.timeInMillis}_${cleanTitle.trim()}"

                    val values = ContentValues().apply {
                        put(CalendarContract.Events.DTSTART, startOfDayUtc.timeInMillis)
                        put(CalendarContract.Events.DTEND, endOfDayUtc.timeInMillis)
                        put(CalendarContract.Events.ALL_DAY, 1)
                        put(CalendarContract.Events.TITLE, cleanTitle.trim())
                        put(CalendarContract.Events.DESCRIPTION, "Academic Calendar Event\n\n$VTOP_SYNC_FOOTPRINT\n[VTOP_ID: $vtopId]")
                        put(CalendarContract.Events.CALENDAR_ID, calendarId)
                        put(CalendarContract.Events.EVENT_TIMEZONE, "UTC")
                        put(CalendarContract.Events.EVENT_COLOR, colorGreen)
                        put(CalendarContract.Events.AVAILABILITY, CalendarContract.Events.AVAILABILITY_FREE)
                    }
                    targetEvents[vtopId] = values
                }
            }

            // ==============================================
            // 4. DIFFING ENGINE: APPLY BATCH OPERATIONS
            // ==============================================
            val existingEvents = mutableMapOf<String, Long>()
            val selection = "(${CalendarContract.Events.CALENDAR_ID} = ?) AND (${CalendarContract.Events.DESCRIPTION} LIKE ?)"
            val selectionArgs = arrayOf(calendarId.toString(), "%$VTOP_SYNC_FOOTPRINT%")
            val projection = arrayOf(CalendarContract.Events._ID, CalendarContract.Events.DESCRIPTION)

            resolver.query(CalendarContract.Events.CONTENT_URI, projection, selection, selectionArgs, null)?.use { cursor ->
                while (cursor.moveToNext()) {
                    val eventId = cursor.getLong(0)
                    val desc = cursor.getString(1)
                    val regex = Regex("\\[VTOP_ID: (.*?)\\]")
                    val vtopId = regex.find(desc)?.groupValues?.get(1)
                    if (vtopId != null) existingEvents[vtopId] = eventId
                }
            }

            val operations = ArrayList<ContentProviderOperation>()
            val processedVtopIds = mutableSetOf<String>()

            // Generate the Sync Adapter URI to bypass delete limits
            val syncUri = getSyncAdapterUri(context, calendarId)

            // Insert or Update Target Events
            targetEvents.forEach { (vtopId, values) ->
                val existingId = existingEvents[vtopId]
                if (existingId != null) {
                    operations.add(
                        ContentProviderOperation.newUpdate(ContentUris.withAppendedId(syncUri, existingId))
                            .withValues(values).build()
                    )
                    processedVtopIds.add(vtopId)
                } else {
                    val eventIndex = operations.size
                    operations.add(ContentProviderOperation.newInsert(syncUri).withValues(values).build())

                    // Attach Reminders using BackReference for Inserts (Leave this as Reminders.CONTENT_URI)
                    val isExam = vtopId.startsWith("EXAM_")
                    val isClass = vtopId.startsWith("CLASS_")
                    if ((isExam && reminderMinutes > 0) || (isClass && reminderMinutes > 0)) {
                        val minutesToRemind = if (isExam) 30 else reminderMinutes
                        operations.add(
                            ContentProviderOperation.newInsert(CalendarContract.Reminders.CONTENT_URI)
                                .withValueBackReference(CalendarContract.Reminders.EVENT_ID, eventIndex)
                                .withValue(CalendarContract.Reminders.MINUTES, minutesToRemind)
                                .withValue(CalendarContract.Reminders.METHOD, CalendarContract.Reminders.METHOD_ALERT).build()
                        )
                    }
                }
            }

            // Delete missing events (using the bypass URI)
            existingEvents.forEach { (vtopId, existingId) ->
                if (!processedVtopIds.contains(vtopId)) {
                    operations.add(ContentProviderOperation.newDelete(ContentUris.withAppendedId(syncUri, existingId)).build())
                }
            }

            resolver.applyBatch(CalendarContract.AUTHORITY, operations)
            Toast.makeText(context, "Calendar synced successfully.", Toast.LENGTH_SHORT).show()

            // Delete missing events
            existingEvents.forEach { (vtopId, existingId) ->
                if (!processedVtopIds.contains(vtopId)) {
                    operations.add(ContentProviderOperation.newDelete(ContentUris.withAppendedId(CalendarContract.Events.CONTENT_URI, existingId)).build())
                }
            }

            resolver.applyBatch(CalendarContract.AUTHORITY, operations)
            Toast.makeText(context, "Calendar synced successfully.", Toast.LENGTH_SHORT).show()

        } catch (e: Exception) {
            android.util.Log.e("CALENDAR_SYNC", e.localizedMessage)
            Toast.makeText(context, "Calendar Sync Failed: ${e.localizedMessage}", Toast.LENGTH_SHORT).show()
        }
    }

    private fun insertReminder(context: Context, eventId: Long, minutes: Int) {
        val reminderValues = ContentValues().apply {
            put(CalendarContract.Reminders.EVENT_ID, eventId)
            put(CalendarContract.Reminders.MINUTES, minutes)
            put(CalendarContract.Reminders.METHOD, CalendarContract.Reminders.METHOD_ALERT)
        }
        context.contentResolver.insert(CalendarContract.Reminders.CONTENT_URI, reminderValues)
    }

    private fun tryParseTime(timeStr: String): Date? {
        // Strip invisible HTML spaces, fix AM/PM gaps, and normalize
        val cleanStr = timeStr.trim().uppercase(Locale.ENGLISH)
            .replace("\u00A0", " ") // Destroys VTOP non-breaking spaces
            .replace("NOON", "PM")
            .replace(".", ":")
            .replace(Regex("(?<=\\d)(AM|PM)"), " $1")
            .replace(Regex("\\s+"), " ")

        val formats = listOf("hh:mm a", "h:mm a", "HH:mm", "H:mm")

        for (f in formats) {
            try {
                val d = SimpleDateFormat(f, Locale.ENGLISH).parse(cleanStr)
                if (d != null) return d
            } catch (_: Exception) {}
        }
        return null
    }
    private fun getNextOccurrenceOfDay(dayOfWeek: Int): Calendar {
        val cal = Calendar.getInstance()
        while (cal.get(Calendar.DAY_OF_WEEK) != dayOfWeek) { cal.add(Calendar.DAY_OF_YEAR, 1) }
        return cal
    }
}